### ISSUE TITLE
Hi Leo, could you please open a new repo for me in the bcgov-IDD group?

### ISSUE THREAD

**Issue by ashlinrichardson** [ll911/prest#1]
Hi Leo, could you please open a new repo for me in the bcgov-IDD group?

Sorry this request is not related to your repo, I was just not sure how to submit an issue for something that wasn't a repo yet.

I would like the new repo to be called, bcstats-craigslist-data

Thanks in adv. for your help
cheers,

Ashlin

**Comment by ll911** [comment]
@ashlinrichardson bcgov-idd is about to merged into bcgov-c, please request via 
https://github.com/BCDevOps/devops-requests/issues
